✨ feat/auth to sales force
GregoireBellon/M1-Architecture-Distribuee pull request #8
Opened 2023-11-17 22:58 UTC by isJlaiel

2023-11-18 16:19 UTC, GregoireBellon requested changes
Attention, il reste des données sensibles dans le code. 

Je pense qu'il est possible d'améliorer la deserialization, la déclaration des paramêtres, ainsi que la configuration du WebClient. 

Mais c'est une très bonne base, et ça fonctionne :partying_face: 

Il faudrait ajouter les tests d'intégrations

2023-11-18 16:19 UTC, GregoireBellon commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/repository/SalesForceCRMRepository.java
> +        private WebClient salesforceWebClient;
N'utilise pas `@Autowired` : ça ne te permet pas de rendre WebClient final. 

salesForceWebClient devrait être private final WebClient.

Avec `@RequiredArgsConstructor`, Spring devrait faire l'injection de dépendance lui même. 

Si tu ne connais pas le concept d'injection de dépendance (essentielle à spring, angular, et même nest !), [baeldung explique tout parfaitement](https://www.baeldung.com/spring-dependency-injection)

2023-11-18 16:19 UTC, GregoireBellon commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/repository/SalesForceCRMRepository.java
> +            int _highAnnualRevenue = (int) highAnnualRevenue ;
tu peux faire la conversion à la volée dans ta query

2023-11-18 16:19 UTC, GregoireBellon commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/repository/SalesForceCRMRepository.java
> +                " AND AnnualRevenue < " + _highAnnualRevenue;
Tu peux utiliser String.format ici. Attention à ne pas oublier le state !

2023-11-18 16:19 UTC, GregoireBellon commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/repository/SalesForceCRMRepository.java
> +                }
Le WebClient de spring peut gérer pour toi toute cette conversion.

Tu as un exemple dans [OpenStreetMapRepository](https://github.com/GregoireBellon/M1-Architecture-Distribuee/blob/dev/VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/repository/OpenStreetMapRepository.java)

2023-11-18 16:19 UTC, GregoireBellon commented on VirtualCRM/src/main/resources/application.properties
> +oauth2.base-path=https://universit3-dev-ed.develop.my.salesforce.com/services/data/v59.0
🚨🚨 C'EST TRES DANGEREUX, TOUT DEVRAIT ÊTRE DANS LE FICHIER .ENV 🚨🚨

2023-11-18 16:19 UTC, GregoireBellon commented on VirtualCRM/src/test/java/com/ArchiDistribuee/VirtualCRM/Config/WebClientConfigTest.java
C'est intéressant de faire ce genre de test, mais c'est pas ceux qui te donne le plus de valeur ajoutée. 

Pour te faciliter la vie, tu aurai pu tester directement ton repository, comme je l'ai fait dans le [InternalLeadRepository](https://github.com/GregoireBellon/M1-Architecture-Distribuee/blob/dev/VirtualCRM/src/integrationTest/java/com/ArchiDistribuee/VirtualCRM/repository/InternalCRMRepositoryIntegrationTest.java) (attention néanmoins : il faut mettre VirtualCrmApplication.class en paramêtre de SpringBootTest)

J'insiste sur ce point, ça t'aurai permis de gagner du temps, car tu n'aurais pas eu à utiliser postman, ça t'aurai facilité la tâche pour débugger, et tu aurais pu itérer plus facilement et plus vite. Aussi, ça t'aurai permis d'isoler chaque soucis, pour bien comprendre ce qui les causait. 

Cette approche qui consite à écrire les tests AVANT de développer, et de s'en servir comme support, et pas seulement comme validation, s'appelle le Test Driven Development (TDD). Si ça t'intéresse, tu peux checker [cet article](https://www.baeldung.com/cs/unit-testing-vs-tdd)

2023-11-18 16:19 UTC, GregoireBellon commented on VirtualCRM/src/test/java/com/ArchiDistribuee/VirtualCRM/Config/WebClientConfigTest.java
> +}
Pareil, c'est cool comme tests, mais ça te permet pas de valider la partie critique : celle de récupération des données depuis SalesForce. 

Avec ces tests, tu ne sais pas si ton repository fonctionne, alors qu'en testant ton repository, tu sais si la configuration fonctionne !

2023-11-18 16:19 UTC, GregoireBellon commented on VirtualCRM/src/test/java/com/ArchiDistribuee/VirtualCRM/VirtualCrmApplicationTests.java
Il faudrait soit décommenter ça, soit le supprimer

2023-11-18 16:29 UTC, isJlaiel commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/Config/OAuth2ClientConfig.java
> +        private String basePath;
c'est ce que je fais . J’utilise bien l'injection de dépendance ici

2023-11-18 16:38 UTC, isJlaiel commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/Config/OAuth2ClientConfig.java
> +        private String basePath;
j'ai déjà essayé de les mettre en final mais je doit ajouter un constructeur pour l'initialiser  .Donc le code devient je trouve àa pas trés beau :P chepa tu penses quoi ? `@Value("${oauth2.username}")
private final String username;

@Value("${oauth2.password}")
private final String password;

public OAuth2ClientConfig(@Value("${oauth2.username}") String username, @Value("${oauth2.password}") String password) {
    this.username = username;
    this.password = password;
}`

2023-11-18 16:57 UTC, isJlaiel commented on VirtualCRM/src/main/resources/application.properties
> +oauth2.base-path=https://universit3-dev-ed.develop.my.salesforce.com/services/data/v59.0
J'ai bcp essayé de les mettre dans un fichier .env et de les appeler depuis application.properties avec ${}, mais l'application n'a jamais réussi à récupérer les valeurs depuis le fichier .env

2023-11-18 17:00 UTC, isJlaiel commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/Config/OAuth2ClientConfig.java
> +                        }
oAuth2AuthorizeRequest.getClientRegistrationId()  prend comme valeur salesForce .
la partie de code c'est pour configure AuthorizedClientManager
puisque on essaye  de se connecter à salesForce avec username , password

2023-11-18 17:37 UTC, GregoireBellon commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/Config/OAuth2ClientConfig.java
> +        private String basePath;
Regarde l'article que je t'ai mis en lien, l'injection de dépendance repose sur le constructeur. Ici ce n'est pas de l'injection de dépendance. C'est juste spring qui utilise les setters

2023-11-18 17:37 UTC, GregoireBellon commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/Config/OAuth2ClientConfig.java
> +        private String basePath;
Le deuxième est mieux, car le serveur plantera si il ne trouve pas oauth2.username et password dans le fichier de conf. Ca évite d'avoir affaire à des bugs invisibles

2023-11-18 17:37 UTC, GregoireBellon commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/Config/OAuth2ClientConfig.java
> +                        }
je parle spécifiquement de la ligne 52 à 59 ! Pourquoi y a il un if ?

2023-11-19 09:42 UTC, GregoireBellon commented on VirtualCRM/src/main/resources/application.properties
> +oauth2.base-path=https://universit3-dev-ed.develop.my.salesforce.com/services/data/v59.0
Tu peux t'inspirer des autres endroits dans le projet où on a fait ça. 

[Cet article parle du lien entre les variables d'env et les variables application.properties](https://www.baeldung.com/spring-boot-properties-env-variables)

Il faudra que tu reset la branche après avoir corrigé ça, car ces variables ne doivent pas apparaitre dans l'historique git

2023-11-23 11:47 UTC, isJlaiel commented on VirtualCRM/src/main/java/com/ArchiDistribuee/VirtualCRM/Config/OAuth2ClientConfig.java
> +                        }
En gros, il gère les infos de connexion (user et mdp) pour Salesforce .
Le map est  utilisée par authorizedClientManager pour réaliser l'authentification  lors des requêtes vers Salesforce

2023-11-26 11:20 UTC, GregoireBellon approved these changes

2023-11-30 12:26 UTC, merged